# -*- coding: utf-8 -*-
"""heatmap_kas_unis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlaiqvYhCQIBlqEVtppGtQJSNje1rMTh
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Data, taken from the 'Counts' sheet of the master file, and removing the decimals
data = {
    'University': ['OU', 'RU', 'RUG', 'TU/e', 'TUD', 'UL', 'UT', 'UU', 'UVA', 'VU'],
    'Requirements': [8, 3, 2, 14, 0, 5, 6, 10, 3, 7],
    'Architecture': [4, 3, 9, 7, 4, 8, 9, 7, 0, 9],
    'Design': [15, 3, 11, 10, 0, 3, 9, 5, 3, 9],
    'Construction\n & Programming': [23, 13, 23, 10, 11, 18, 15, 24, 45, 21],
    'Testing': [8, 6, 0, 7, 11, 5, 6, 5, 5, 5],
    'SE Operations': [4, 6, 2, 3, 4, 10, 3, 2, 5, 2],
    'Maintenance': [4, 0, 7, 7, 14, 5, 6, 0, 5, 7],
    'Configuration\n mgmt': [4, 0, 7, 7, 4, 0, 0, 0, 3, 2],
    'SE management': [0, 13, 9, 3, 11, 10, 6, 2, 3, 9],
    'SE process': [8, 9, 9, 3, 7, 10, 3, 7, 8, 5],
    'SE models': [12, 9, 7, 14, 4, 0, 12, 10, 5, 9],
    'SW Security': [4, 3, 2, 0, 11, 8, 6, 5, 3, 5],
    'SE Economics': [0, 3, 0, 0, 4, 3, 3, 7, 3, 2],
    'Verification': [4, 13, 5, 10, 7, 10, 15, 7, 5, 5],
    'PL design': [4, 16, 7, 3, 11, 5, 3, 10, 8, 2]
}

# 2. Create DataFrame and set University as the index
df = pd.DataFrame(data)
df.set_index('University', inplace=True)

# 3. Transpose the data (flip rows and columns)
df_transposed = df.T

# 4. Initialize the plot
# Adjusting figsize to (10, 12) ensures labels aren't squashed
plt.figure(figsize=(10, 12))

# 5. Create the heatmap
# annot=True puts the numbers in the cells
# cmap='YlGnBu' gives it the yellow-to-blue color scheme
sns.set(font_scale=1.3)
sns.heatmap(df_transposed, annot=True, cmap='YlGnBu', fmt='g', cbar_kws={'label': 'Percentage (%)'})

# 6. Formatting
plt.title(None)
plt.xlabel(None)
plt.ylabel(None)

# 7. Final layout adjustment and save
plt.tight_layout()
plt.savefig('heatmap_transposed.pdf', dpi=300)

plt.show()